### ISSUE TITLE
셔틀버스 정류장 위도 경도

### ISSUE THREAD

**Issue by pasa3232** [wafflestudio/shuttlebus-backend#19]
다음 셔틀버스 정류장의 위도와 경도를 조사해야함. (WGS 84 기준)

□ 행정관

․ 행정관 잔디광장 앞

설입 방면, 대학동 방면, 사당 방면 3개 정류장이 있음. 각각 정보가 필요함.

□ 서울대입구역

․ 서울대입구역 3번 출구 관악구청 방향 롯데리아 앞
행정관 방면, 공대 방면 2개 정류장이 있음. 각각 정보가 필요함.

□ 대학동

․ 서울정보학교 인근 세븐일레븐 앞

□ 사당역

․ 사당역 4번출구 남태령 방면 350m 지점 (홈플러스 타이어O뱅크 부근)

□ 낙성대

․ 송원숯불갈비

**Comment by yblee2001** [comment]
행정관:
1. 설입 방면 / 대학동 방면 / 사당 방면: 37.460117273317294, 126.95125289767172
(요즘 공사도 하고 그래서 정확한 셔틀 위치는 잘 모르겠습니다 ㅠㅠ 일단 행정관 좌표 올려놨는데 다음에 학교 가봐서 찾아보겠습니다.. 일단 이걸루 넣어주세요)

서울대입구역:
1. 관악구청 방향 (5511, 5513, 5515 지나가는 올영 앞): 37.48072904959792, 126.95243201193229
2. 행정관 방면 셔틀: 37.47975062517101, 126.95231970719348
3. 공대 방면 셔틀 (이거 다시 가서 확인해봐야되는데 일단 이걸루 넣어주세요): 37.47936273181645, 126.95225718405017

대학동
1. 서울산업정보고등학교 인근 세븐일레븐 앞 (녹셔 타본적이 없어서 일단 세븐으로 찍었습니다 이것도 나중에 확인필요): 37.47047703002356, 126.94075543792523

사당역:
1. 사당역 4출 남태령 방면 (홈플러스 / 타이어뱅크 사이로 찍었습니다): 37.47231237956838, 126.98268796943321

낙성대:
1. 송원숯불갈비 (차이나당 앞에): 37.47701191204649, 126.95897017903555
